# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0004_auto_20180106_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sueveyId',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
