# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0006_auto_20180106_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageType', models.BooleanField()),
                ('text', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text9',
        ),
        migrations.AddField(
            model_name='message',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatty.Post'),
        ),
    ]
