# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0007_auto_20180107_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messageType',
            new_name='human',
        ),
    ]
